const counter_types = {
  INCREMENT_COUNTER: "INCREMENT_COUNTER",
  DECREMENT_COUNTER: "DECREMENT_COUNTER",
  RESET_COUNTER: "RESET_COUNTER",
  INPUT_VALUE: "INPUT_VALUE",
};

export default counter_types;
